In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier

C:\Users\codyb\Anaconda3\envs\NewPythonData\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d

In [27]:
mvps = pd.read_csv('MVP_Players_Info_Fixed.csv')
mvps["fullName"] = mvps["nameFirst"]+" "+mvps["nameLast"]
mvps

,Unnamed: 0,awardID,yearID,lgID_mvp,playerID,pointsWon,pointsMax,votesFirst,lgID_batting,teamID,nameFirst,nameLast,nameGiven,retroID,bbrefID,fullName
0,0,MVP,1931,AL,averiea01,43,80,NaN,AL,CLE,Earl,Averill,Howard Earl,avere101,averiea01,Earl Averill
1,1,MVP,1931,AL,bluelu01,4,80,0.0,AL,CHA,Lu,Blue,Luzerne Atwell,bluel101,bluelu01,Lu Blue
2,2,MVP,1931,AL,chapmbe01,7,80,0.0,AL,NYA,Ben,Chapman,William Benjamin,chapb102,chapmbe01,Ben Chapman
3,3,MVP,1931,AL,cochrmi01,16,80,NaN,AL,PHA,Mickey,Cochrane,Gordon Stanley,cochm101,cochrmi01,Mickey Cochrane
4,4,MVP,1931,AL,cronijo01,18,80,NaN,AL,WS1,Joe,Cronin,Joseph Edward,cronj101,cronijo01,Joe Cronin
5,5,MVP,1931,AL,earnsge01,12,80,NaN,AL,PHA,George,Earnshaw,George Livingston,earng101,earnsge01,George Earnshaw
6,6,MVP,1931,AL,ferrewe01,12,80,NaN,AL,CLE,Wes,Ferrell,Wesley Cheek,ferrw101,ferrewe01,Wes Ferrell
7,7,MVP,1931,AL,foxxji01,1,80,0.0,AL,PHA,Jimmie,Foxx,James Emory,foxxj101,foxxji01,Jimmie Foxx
8,8,MVP,1931,AL,gehrich01,4,80,0.0,AL,DET,Charlie,Gehringer,Charles Leonard,gehrc101,gehrich01,Charlie Gehringer
9,9,MVP,1931,AL,gehrilo01,59,80,NaN,AL,NYA,Lou,Gehrig,Henry Louis,gehrl101,gehrilo01,Lou Gehrig
10,10,MVP,1931,AL,gosligo01,2,80,0.0,AL,SLA,Goose,Goslin,Leon Allen,goslg101,gosligo01,Goose Goslin
11,11,MVP,1931,AL,grovele01,78,80,NaN,AL,PHA,Lefty,Grove,Robert Moses,grovl101,grovele01,Lefty Grove
12,12,MVP,1931,AL,kressre01,3,80,0.0,AL,SLA,Red,Kress,Ralph,kresr101,kressre01,Red Kress
13,13,MVP,1931,AL,macfada01,2,80,0.0,AL,BOS,Danny,MacFayden,Daniel Knowles,macfd101,macfada01,Danny MacFayden
14,14,MVP,1931,AL,marbefi01,11,80,NaN,AL,WS1,Firpo,Marberry,Frederick,marbf101,marbefi01,Firpo Marberry
15,15,MVP,1931,AL,melilsk01,17,80,NaN,AL,SLA,Ski,Melillo,Oscar Donald,melis101,melilsk01,Ski Melillo
16,16,MVP,1931,AL,oliveto01,2,80,0.0,AL,BOS,Tom,Oliver,Thomas Noble,olivt101,oliveto01,Tom Oliver
17,17,MVP,1931,AL,reynoca01,2,80,0.0,AL,CHA,Carl,Reynolds,Carl Nettles,reync102,reynoca01,Carl Reynolds
18,18,MVP,1931,AL,rhyneha01,10,80,NaN,AL,BOS,Hal,Rhyne,Harold J.,rhynh101,rhyneha01,Hal Rhyne
19,19,MVP,1931,AL,ruthba01,40,80,NaN,AL,NYA,Babe,Ruth,George Herman,ruthb101,ruthba01,Babe Ruth
20,20,MVP,1931,AL,simmoal01,51,80,NaN,AL,PHA,Al,Simmons,Aloysius Harry,simma101,simmoal01,Al Simmons
21,21,MVP,1931,AL,stewale01,2,80,0.0,AL,SLA,Lefty,Stewart,Walter Cleveland,stewl101,stewale01,Lefty Stewart
22,22,MVP,1931,AL,stonejo01,6,80,0.0,AL,DET,John,Stone,John Thomas,stonj102,stonejo01,John Stone
23,23,MVP,1931,AL,webbea01,22,80,NaN,AL,BOS,Earl,Webb,William Earl,webbe101,webbea01,Earl Webb
24,24,MVP,1931,AL,westsa01,16,80,NaN,AL,WS1,Sam,West,Samuel Filmore,wests101,westsa01,Sam West
25,25,MVP,1931,NL,adamssp01,18,80,NaN,NL,SLN,Sparky,Adams,Earl John,adams101,adamssp01,Sparky Adams
26,26,MVP,1931,NL,bartedi01,2,80,0.0,NL,PHI,Dick,Bartell,Richard William,bartd101,bartedi01,Dick Bartell
27,27,MVP,1931,NL,bottoji01,8,80,0.0,NL,SLN,Jim,Bottomley,James Leroy,bottj101,bottoji01,Jim Bottomley
28,28,MVP,1931,NL,branded01,15,80,NaN,NL,BSN,Ed,Brandt,Edward Arthur,brane101,branded01,Ed Brandt
29,29,MVP,1931,NL,clarkwa02,3,80,0.0,NL,BRO,Watty,Clark,William Watson,clarw101,clarkwa02,Watty Clark
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4879,4879,MVP,2018,AL,NaN,9,420,0.0,NaN,NaN,Xander,Bogaerts,NaN,NaN,bogaexa01,Xander Bogaerts
4880,4880,MVP,2018,AL,NaN,7,420,0.0,NaN,NaN,Andrelton,Simmons,NaN,NaN,simmoan01,Andrelton Simmons
4881,4881,MVP,2018,AL,NaN,7,420,0.0,NaN,NaN,Blake,Treinen,NaN,NaN,treinbl01,Blake Treinen
4882,4882,MVP,2018,AL,NaN,6,420,0.0,NaN,NaN,Whit,Merrifield,NaN,NaN,merriwh01,Whit Merrifield
4883,4883,MVP,2018,AL,NaN,5,420,0.0,NaN,NaN,Edwin,Diaz,NaN,NaN,diazed04,Edwin Diaz
4884,4884,MVP,2018,AL,NaN,4,420,0.0,NaN,NaN,Giancarlo,Stanton,NaN,NaN,stantmi03,Giancarlo Stanton
4885,4885,MVP,2018,AL,NaN,3,420,0.0,NaN,NaN,Didi,Gregorius,NaN,NaN,gregodi01,Didi Gregorius
4886,4886,MVP,2018,AL,NaN,3,420,0.0,NaN,NaN,Jed,Lowrie,NaN,NaN,lowrije01,Jed Lowrie
4887,4887,MVP,2018,AL,NaN,1,420,0.0,NaN,NaN,Trevor,Bauer,NaN,NaN,bauertr01,Trevor Bauer
4888,4888,MVP,2018,AL,NaN,1,420,0.0,NaN,NaN,Aaron,Hicks,NaN,NaN,hicksaa01,Aaron Hicks
4889,4889,MVP,2018,AL,NaN,1,420,0.0,NaN,NaN,Chris,Sale,NaN,NaN,salech01,Chris Sale
4890,4890,MVP,2018,NL,NaN,415,420,29.0,NaN,NaN,Christian,Yelich,NaN,NaN,yelicch01,Christian Yelich
4891,4891,MVP,2018,NL,NaN,250,420,0.0,NaN,NaN,Javier,Baez,NaN,NaN,baezja01,Javier Baez
4892,4892,MVP,2018,NL,NaN,203,420,0.0,NaN,NaN,Nolan,Arenado,NaN,NaN,arenano01,Nolan Arenado
4893,4893,MVP,2018,NL,NaN,174,420,0.0,NaN,NaN,Freddie,Freeman,NaN,NaN,freemfr01,Freddie Freeman
4894,4894,MVP,2018,NL,NaN,141,420,1.0,NaN,NaN,Jacob,deGrom,NaN,NaN,degroja01,Jacob deGrom
4895,4895,MVP,2018,NL,NaN,115,420,0.0,NaN,NaN,Paul,Goldschmidt,NaN,NaN,goldspa01,Paul Goldschmidt
4896,4896,MVP,2018,NL,NaN,109,420,0.0,NaN,NaN,Lorenzo,Cain,NaN,NaN,cainlo01,Lorenzo Cain
4897,4897,MVP,2018,NL,NaN,108,420,0.0,NaN,NaN,Trevor,Story,NaN,NaN,storytr01,Trevor Story
4898,4898,MVP,2018,NL,NaN,105,420,0.0,NaN,NaN,Matt,Carpenter,NaN,NaN,carpema01,Matt Carpenter
4899,4899,MVP,2018,NL,NaN,59,420,0.0,NaN,NaN,Max,Scherzer,NaN,NaN,scherma01,Max Scherzer
4900,4900,MVP,2018,NL,NaN,21,420,0.0,NaN,NaN,Anthony,Rendon,NaN,NaN,rendoan01,Anthony Rendon
4901,4901,MVP,2018,NL,NaN,19,420,0.0,NaN,NaN,Ronald,Acuna,NaN,NaN,acunaro01,Ronald Acuna
4902,4902,MVP,2018,NL,NaN,16,420,0.0,NaN,NaN,Aaron,Nola,NaN,NaN,nolaaa01,Aaron Nola
4903,4903,MVP,2018,NL,NaN,10,420,0.0,NaN,NaN,Justin,Turner,NaN,NaN,turneju01,Justin Turner
4904,4904,MVP,2018,NL,NaN,8,420,0.0,NaN,NaN,Max,Muncy,NaN,NaN,muncyma01,Max Muncy
4905,4905,MVP,2018,NL,NaN,7,420,0.0,NaN,NaN,Jesus,Aguilar,NaN,NaN,aguilje01,Jesus Aguilar
4906,4906,MVP,2018,NL,NaN,6,420,0.0,NaN,NaN,Anthony,Rizzo,NaN,NaN,rizzoan01,Anthony Rizzo
4907,4907,MVP,2018,NL,NaN,2,420,0.0,NaN,NaN,Nick,Markakis,NaN,NaN,markani01,Nick Markakis
4908,4908,MVP,2018,NL,NaN,2,420,0.0,NaN,NaN,Eugenio,Suarez,NaN,NaN,suareeu01,Eugenio Suarez

In [28]:
from pybaseball import playerid_reverse_lookup
id_lookup = playerid_reverse_lookup(list(mvps['bbrefID']), key_type='bbref')
id_lookup_df = pd.DataFrame(id_lookup[['key_bbref','key_fangraphs']])
id_lookup_df.head()

Gathering player lookup table. This may take a moment.

   key_bbref  key_fangraphs
0  aaronha01        1000001
1  abernte02        1000020
2  abramca01        1000025
3  abreubo01            945
4  abreujo02          15676

In [29]:
mvps_full = mvps.merge(id_lookup_df, left_on="bbrefID", right_on="key_bbref", how="left")
mvps_full

,Unnamed: 0,awardID,yearID,lgID_mvp,playerID,pointsWon,pointsMax,votesFirst,lgID_batting,teamID,nameFirst,nameLast,nameGiven,retroID,bbrefID,fullName,key_bbref,key_fangraphs
0,0,MVP,1931,AL,averiea01,43,80,NaN,AL,CLE,Earl,Averill,Howard Earl,avere101,averiea01,Earl Averill,averiea01,1000378
1,1,MVP,1931,AL,bluelu01,4,80,0.0,AL,CHA,Lu,Blue,Luzerne Atwell,bluel101,bluelu01,Lu Blue,bluelu01,1001093
2,2,MVP,1931,AL,chapmbe01,7,80,0.0,AL,NYA,Ben,Chapman,William Benjamin,chapb102,chapmbe01,Ben Chapman,chapmbe01,1002141
3,3,MVP,1931,AL,cochrmi01,16,80,NaN,AL,PHA,Mickey,Cochrane,Gordon Stanley,cochm101,cochrmi01,Mickey Cochrane,cochrmi01,1002384
4,4,MVP,1931,AL,cronijo01,18,80,NaN,AL,WS1,Joe,Cronin,Joseph Edward,cronj101,cronijo01,Joe Cronin,cronijo01,1002796
5,5,MVP,1931,AL,earnsge01,12,80,NaN,AL,PHA,George,Earnshaw,George Livingston,earng101,earnsge01,George Earnshaw,earnsge01,1003633
6,6,MVP,1931,AL,ferrewe01,12,80,NaN,AL,CLE,Wes,Ferrell,Wesley Cheek,ferrw101,ferrewe01,Wes Ferrell,ferrewe01,1004010
7,7,MVP,1931,AL,foxxji01,1,80,0.0,AL,PHA,Jimmie,Foxx,James Emory,foxxj101,foxxji01,Jimmie Foxx,foxxji01,1004285
8,8,MVP,1931,AL,gehrich01,4,80,0.0,AL,DET,Charlie,Gehringer,Charles Leonard,gehrc101,gehrich01,Charlie Gehringer,gehrich01,1004596
9,9,MVP,1931,AL,gehrilo01,59,80,NaN,AL,NYA,Lou,Gehrig,Henry Louis,gehrl101,gehrilo01,Lou Gehrig,gehrilo01,1004598
10,10,MVP,1931,AL,gosligo01,2,80,0.0,AL,SLA,Goose,Goslin,Leon Allen,goslg101,gosligo01,Goose Goslin,gosligo01,1004893
11,11,MVP,1931,AL,grovele01,78,80,NaN,AL,PHA,Lefty,Grove,Robert Moses,grovl101,grovele01,Lefty Grove,grovele01,1005099
12,12,MVP,1931,AL,kressre01,3,80,0.0,AL,SLA,Red,Kress,Ralph,kresr101,kressre01,Red Kress,kressre01,1007160
13,13,MVP,1931,AL,macfada01,2,80,0.0,AL,BOS,Danny,MacFayden,Daniel Knowles,macfd101,macfada01,Danny MacFayden,macfada01,1007904
14,14,MVP,1931,AL,marbefi01,11,80,NaN,AL,WS1,Firpo,Marberry,Frederick,marbf101,marbefi01,Firpo Marberry,marbefi01,1008100
15,15,MVP,1931,AL,melilsk01,17,80,NaN,AL,SLA,Ski,Melillo,Oscar Donald,melis101,melilsk01,Ski Melillo,melilsk01,1008748
16,16,MVP,1931,AL,oliveto01,2,80,0.0,AL,BOS,Tom,Oliver,Thomas Noble,olivt101,oliveto01,Tom Oliver,oliveto01,1009780
17,17,MVP,1931,AL,reynoca01,2,80,0.0,AL,CHA,Carl,Reynolds,Carl Nettles,reync102,reynoca01,Carl Reynolds,reynoca01,1010864
18,18,MVP,1931,AL,rhyneha01,10,80,NaN,AL,BOS,Hal,Rhyne,Harold J.,rhynh101,rhyneha01,Hal Rhyne,rhyneha01,1010889
19,19,MVP,1931,AL,ruthba01,40,80,NaN,AL,NYA,Babe,Ruth,George Herman,ruthb101,ruthba01,Babe Ruth,ruthba01,1011327
20,20,MVP,1931,AL,simmoal01,51,80,NaN,AL,PHA,Al,Simmons,Aloysius Harry,simma101,simmoal01,Al Simmons,simmoal01,1011978
21,21,MVP,1931,AL,stewale01,2,80,0.0,AL,SLA,Lefty,Stewart,Walter Cleveland,stewl101,stewale01,Lefty Stewart,stewale01,1012524
22,22,MVP,1931,AL,stonejo01,6,80,0.0,AL,DET,John,Stone,John Thomas,stonj102,stonejo01,John Stone,stonejo01,1012568
23,23,MVP,1931,AL,webbea01,22,80,NaN,AL,BOS,Earl,Webb,William Earl,webbe101,webbea01,Earl Webb,webbea01,1013708
24,24,MVP,1931,AL,westsa01,16,80,NaN,AL,WS1,Sam,West,Samuel Filmore,wests101,westsa01,Sam West,westsa01,1013813
25,25,MVP,1931,NL,adamssp01,18,80,NaN,NL,SLN,Sparky,Adams,Earl John,adams101,adamssp01,Sparky Adams,adamssp01,1000063
26,26,MVP,1931,NL,bartedi01,2,80,0.0,NL,PHI,Dick,Bartell,Richard William,bartd101,bartedi01,Dick Bartell,bartedi01,1000621
27,27,MVP,1931,NL,bottoji01,8,80,0.0,NL,SLN,Jim,Bottomley,James Leroy,bottj101,bottoji01,Jim Bottomley,bottoji01,1001228
28,28,MVP,1931,NL,branded01,15,80,NaN,NL,BSN,Ed,Brandt,Edward Arthur,brane101,branded01,Ed Brandt,branded01,1001348
29,29,MVP,1931,NL,clarkwa02,3,80,0.0,NL,BRO,Watty,Clark,William Watson,clarw101,clarkwa02,Watty Clark,clarkwa02,1002315
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4879,4879,MVP,2018,AL,NaN,9,420,0.0,NaN,NaN,Xander,Bogaerts,NaN,NaN,bogaexa01,Xander Bogaerts,bogaexa01,12161
4880,4880,MVP,2018,AL,NaN,7,420,0.0,NaN,NaN,Andrelton,Simmons,NaN,NaN,simmoan01,Andrelton Simmons,simmoan01,10847
4881,4881,MVP,2018,AL,NaN,7,420,0.0,NaN,NaN,Blake,Treinen,NaN,NaN,treinbl01,Blake Treinen,treinbl01,12572
4882,4882,MVP,2018,AL,NaN,6,420,0.0,NaN,NaN,Whit,Merrifield,NaN,NaN,merriwh01,Whit Merrifield,merriwh01,11281
4883,4883,MVP,2018,AL,NaN,5,420,0.0,NaN,NaN,Edwin,Diaz,NaN,NaN,diazed04,Edwin Diaz,diazed04,14710
4884,4884,MVP,2018,AL,NaN,4,420,0.0,NaN,NaN,Giancarlo,Stanton,NaN,NaN,stantmi03,Giancarlo Stanton,stantmi03,4949
4885,4885,MVP,2018,AL,NaN,3,420,0.0,NaN,NaN,Didi,Gregorius,NaN,NaN,gregodi01,Didi Gregorius,gregodi01,6012
4886,4886,MVP,2018,AL,NaN,3,420,0.0,NaN,NaN,Jed,Lowrie,NaN,NaN,lowrije01,Jed Lowrie,lowrije01,4418
4887,4887,MVP,2018,AL,NaN,1,420,0.0,NaN,NaN,Trevor,Bauer,NaN,NaN,bauertr01,Trevor Bauer,bauertr01,12703
4888,4888,MVP,2018,AL,NaN,1,420,0.0,NaN,NaN,Aaron,Hicks,NaN,NaN,hicksaa01,Aaron Hicks,hicksaa01,5297
4889,4889,MVP,2018,AL,NaN,1,420,0.0,NaN,NaN,Chris,Sale,NaN,NaN,salech01,Chris Sale,salech01,10603
4890,4890,MVP,2018,NL,NaN,415,420,29.0,NaN,NaN,Christian,Yelich,NaN,NaN,yelicch01,Christian Yelich,yelicch01,11477
4891,4891,MVP,2018,NL,NaN,250,420,0.0,NaN,NaN,Javier,Baez,NaN,NaN,baezja01,Javier Baez,baezja01,12979
4892,4892,MVP,2018,NL,NaN,203,420,0.0,NaN,NaN,Nolan,Arenado,NaN,NaN,arenano01,Nolan Arenado,arenano01,9777
4893,4893,MVP,2018,NL,NaN,174,420,0.0,NaN,NaN,Freddie,Freeman,NaN,NaN,freemfr01,Freddie Freeman,freemfr01,5361
4894,4894,MVP,2018,NL,NaN,141,420,1.0,NaN,NaN,Jacob,deGrom,NaN,NaN,degroja01,Jacob deGrom,degroja01,10954
4895,4895,MVP,2018,NL,NaN,115,420,0.0,NaN,NaN,Paul,Goldschmidt,NaN,NaN,goldspa01,Paul Goldschmidt,goldspa01,9218
4896,4896,MVP,2018,NL,NaN,109,420,0.0,NaN,NaN,Lorenzo,Cain,NaN,NaN,cainlo01,Lorenzo Cain,cainlo01,9077
4897,4897,MVP,2018,NL,NaN,108,420,0.0,NaN,NaN,Trevor,Story,NaN,NaN,storytr01,Trevor Story,storytr01,12564
4898,4898,MVP,2018,NL,NaN,105,420,0.0,NaN,NaN,Matt,Carpenter,NaN,NaN,carpema01,Matt Carpenter,carpema01,8090
4899,4899,MVP,2018,NL,NaN,59,420,0.0,NaN,NaN,Max,Scherzer,NaN,NaN,scherma01,Max Scherzer,scherma01,3137
4900,4900,MVP,2018,NL,NaN,21,420,0.0,NaN,NaN,Anthony,Rendon,NaN,NaN,rendoan01,Anthony Rendon,rendoan01,12861
4901,4901,MVP,2018,NL,NaN,19,420,0.0,NaN,NaN,Ronald,Acuna,NaN,NaN,acunaro01,Ronald Acuna,acunaro01,18401
4902,4902,MVP,2018,NL,NaN,16,420,0.0,NaN,NaN,Aaron,Nola,NaN,NaN,nolaaa01,Aaron Nola,nolaaa01,16149
4903,4903,MVP,2018,NL,NaN,10,420,0.0,NaN,NaN,Justin,Turner,NaN,NaN,turneju01,Justin Turner,turneju01,5235
4904,4904,MVP,2018,NL,NaN,8,420,0.0,NaN,NaN,Max,Muncy,NaN,NaN,muncyma01,Max Muncy,muncyma01,13301
4905,4905,MVP,2018,NL,NaN,7,420,0.0,NaN,NaN,Jesus,Aguilar,NaN,NaN,aguilje01,Jesus Aguilar,aguilje01,11342
4906,4906,MVP,2018,NL,NaN,6,420,0.0,NaN,NaN,Anthony,Rizzo,NaN,NaN,rizzoan01,Anthony Rizzo,rizzoan01,3473
4907,4907,MVP,2018,NL,NaN,2,420,0.0,NaN,NaN,Nick,Markakis,NaN,NaN,markani01,Nick Markakis,markani01,5930
4908,4908,MVP,2018,NL,NaN,2,420,0.0,NaN,NaN,Eugenio,Suarez,NaN,NaN,suareeu01,Eugenio Suarez,suareeu01,12552

In [34]:
batting = pd.read_csv("BattingDataFG.csv")
pitching = pd.read_csv("PitchingDataFG.csv")
fielding = pd.read_csv("FieldingDataFG.csv")
records = pd.read_csv("TeamRecords.csv")
fielding.head()

,Season,Name,Team,Pos,G,GS,Inn,PO,A,E,...,DPT,DPF,Scp,SB,CS,PB,WP,FP,TZ,playerid
0,1989,Barry Bonds,PIT,LF,156,146.0,1338.0,366,14,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.985,37.0,1109
1,1999,Andruw Jones,ATL,CF,162,162.0,1447.1,493,13,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.981,36.0,96
2,1975,Mark Belanger,BAL,SS,152,138.0,1262.1,259,508,17,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.978,35.0,1000786
3,1998,Andruw Jones,ATL,CF,159,156.0,1372.2,413,20,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.995,35.0,96
4,1968,Brooks Robinson,BAL,3B,162,161.0,1435.0,168,353,16,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.970,33.0,1011055

In [23]:
#merge batting, pitching, fielding
full_1 = batting.merge(pitching, on=["playerid","Season"], how="outer", suffixes=("_bat","_pit"))
full_2 = full_1.merge(fielding[["Season","Pos","FP","playerid"]], on=["playerid","Season"], how="outer", suffixes=("","_fld"))
full_2.head()

,Season,Name_bat,Team_bat,Age_bat,G_bat,PA,H_bat,1B,2B,3B,...,BB_pit,SO,K/9,BB/9,K/BB,WHIP,FIP,WAR_pit,Pos,FP
0,1963,Buster Narum,Orioles,22.0,7.0,1.0,1.0,0.0,0.0,0.0,...,5.0,5.0,5.00,5.00,1.00,1.44,3.03,0.1,P,1.000
1,2010,Gustavo Chacin,Astros,29.0,44.0,1.0,1.0,0.0,0.0,0.0,...,20.0,31.0,7.28,4.70,1.55,1.85,4.04,0.1,P,0.800
2,1938,Bill Lefebvre,Red Sox,22.0,1.0,1.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.00,0.00,0.00,2.00,10.17,-0.2,P,0.000
3,2008,Felix Hernandez,Mariners,22.0,31.0,2.0,1.0,0.0,0.0,0.0,...,80.0,175.0,7.85,3.59,2.19,1.39,3.80,3.3,P,0.978
4,2005,Eddie Rogers,Orioles,26.0,8.0,1.0,1.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SS,0.000

In [45]:
records.columns

Index(['yearID', 'lgID', 'teamID', 'franchID', 'divID', 'Rank', 'G', 'Ghome',
       'W', 'L', 'DivWin', 'WCWin', 'LgWin', 'WSWin', 'R', 'AB', 'H', '2B',
       '3B', 'HR', 'BB', 'SO', 'SB', 'CS', 'HBP', 'SF', 'RA', 'ER', 'ERA',
       'CG', 'SHO', 'SV', 'IPouts', 'HA', 'HRA', 'BBA', 'SOA', 'E', 'DP', 'FP',
       'name', 'park', 'attendance', 'BPF', 'PPF', 'teamIDBR',
       'teamIDlahman45', 'teamIDretro', 'Playoffs'],
      dtype='object')

In [47]:
full_3 = full_2.merge(mvps_full,left_on=["Season","playerid"],right_on=["yearID","key_fangraphs"],how="outer")
full_3.columns

Index(['Season', 'Name_bat', 'Team_bat', 'Age_bat', 'G_bat', 'PA', 'H_bat',
       '1B', '2B', '3B', 'HR_bat', 'R_bat', 'RBI', 'BB_bat', 'SB', 'AVG',
       'OBP', 'SLG', 'OPS', 'wOBA', 'WAR_bat', 'playerid', 'Name_pit',
       'Team_pit', 'Season.1', 'Age_pit', 'W', 'L', 'ERA', 'G_pit', 'GS', 'CG',
       'ShO', 'SV', 'BS', 'IP', 'H_pit', 'R_pit', 'ER', 'HR_pit', 'BB_pit',
       'SO', 'K/9', 'BB/9', 'K/BB', 'WHIP', 'FIP', 'WAR_pit', 'Pos', 'FP',
       'Unnamed: 0', 'awardID', 'yearID', 'lgID_mvp', 'playerID', 'pointsWon',
       'pointsMax', 'votesFirst', 'lgID_batting', 'teamID', 'nameFirst',
       'nameLast', 'nameGiven', 'retroID', 'bbrefID', 'fullName', 'key_bbref',
       'key_fangraphs'],
      dtype='object')

In [50]:
#merge team win% & playoffs
records.loc[(records["DivWin"]=="Y") | (records["WCWin"]=="Y") | (records["LgWin"]=="Y"), "Playoffs"] = 1
records["Playoffs"] = records["Playoffs"].replace(np.nan, 0)

full_df = full_3.merge(records,left_on=["Season","teamID"],right_on=["yearID","teamID"],how="left")
full_df.describe()

,Season,Age_bat,G_bat,PA,H_bat,1B,2B_x,3B_x,HR_bat,R_bat,...,HRA,BBA,SOA,E,DP,FP_y,attendance,BPF,PPF,Playoffs
count,112807.000000,104799.000000,104799.000000,104799.000000,104799.000000,104799.000000,104799.000000,104799.000000,104799.000000,104799.000000,...,6575.000000,6575.000000,6575.000000,6575.000000,6575.000000,6575.000000,6.575000e+03,6575.000000,6575.000000,6575.000000
mean,1984.620192,27.963607,68.436264,212.087778,49.137587,34.420204,8.744148,1.307264,4.665970,24.615617,...,125.585551,513.834068,851.481825,131.554829,150.045171,0.978428,1.643729e+06,100.604411,100.034677,0.327300
std,23.313230,4.179818,48.602495,214.560231,54.016151,37.542152,10.370008,2.160135,7.590064,28.463227,...,36.886954,75.976056,231.414292,30.234279,20.208058,0.004765,9.014140e+05,4.739038,4.860514,0.469264
min,1931.000000,16.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,33.000000,257.000000,310.000000,54.000000,74.000000,0.957000,8.092200e+04,88.000000,88.000000,0.000000
25%,1968.000000,25.000000,26.000000,25.000000,4.000000,3.000000,0.000000,0.000000,0.000000,2.000000,...,100.000000,464.000000,667.000000,110.000000,137.000000,0.975000,9.443910e+05,97.000000,97.000000,0.000000
50%,1988.000000,27.000000,60.000000,127.000000,26.000000,19.000000,4.000000,0.000000,1.000000,13.000000,...,125.000000,507.000000,856.000000,130.000000,149.000000,0.979000,1.467020e+06,100.000000,100.000000,0.000000
75%,2004.000000,31.000000,111.000000,370.000000,85.000000,59.000000,15.000000,2.000000,6.000000,40.000000,...,152.500000,564.000000,1017.000000,151.000000,164.000000,0.982000,2.285018e+06,103.000000,103.000000,1.000000
max,2018.000000,58.000000,165.000000,778.000000,262.000000,225.000000,67.000000,23.000000,73.000000,167.000000,...,258.000000,812.000000,1510.000000,267.000000,217.000000,0.991000,4.483350e+06,129.000000,129.000000,1.000000

In [32]:
full_df['MVP_Classification']=full_df['awardID']
full_df['MVP_Classification'] = full_df['MVP_Classification'].map({'MVP': 1})
full_df['MVP_Classification'] = full_df['MVP_Classification'].replace(np.nan, 0)

In [33]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
from sklearn.model_selection import train_test_split
y=full_df.loc[full_df["Season"]==2018]['MVP_Classification']
X=full_df.loc[full_df["Season"]==2018].drop(['MVP_Classification','awardID', 'Name','Lev', 'Tm', 'Age'], axis=1)
X = X.fillna(value=0)
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)